version: 2
jobs:
  build:
    branches:
      only:
        - develop
    docker:
      - image: circleci/node:stretch
    environment:
      LOL: u
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "c8:24:98:b2:c4:df:97:b4:8b:34:e6:48:05:8f:de:f9"    
      - run:
          command: |
            cd frontend
            yarn
            yarn build
            cd build
            ls -la
      - run:
          command: |
            cd backend
            yarn
      - run:
          command: |
            mkdir -p ~/.ssh
            echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
      - run:
          command: | 
            echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run: # change this to deploy; but docs said it would be disabled with ssh usages
          name: deploy
          command: |
            sudo apt update -y && sudo apt install -y rsync
            if [ "${CIRCLE_BRANCH}" = "develop" ]; then
              rsync -avce ssh ./frontend/build matt@matthewpetschl.com:/home/matt/www/lol
            else
              echo "Not master branch, dry run only"
            fi            
  # deploy:
    # branches:
      # only:
        # - master
    # docker:
      # image: ubuntu:latest
    # steps:
      # - add_ssh_keys:
          # fingerprints:
            # - "4f:10:06:b3:ac:b5:5f:c6:ef:7f:a9:cb:5d:33:9d:10"
      # - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      # - run: # change this to deploy; but docs said it would be disabled with ssh usages
          # name: deploy
          # command: |
            # if [ "${CIRCLE_BRANCH}" = "master" ]; then
              # rsync -avce ssh ./frontend/build root@matthewpetschl.com:/www/lol
            # else
              # echo "Not master branch, dry run only"
            # fi
# 
# workflows:
  # version: 2
  # build_and_deploy:
    # jobs:
      # - build
      # - deploy:
          # requires:
            # - build