version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:latest
    environment:
      LOL: u
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            yarn
            yarn build
            cd build
            ls -la
      - run:
          command: |
            cd backend
            yarn
  deploy:
    branches:
      only:
        - master
    docker:
      image: ubuntu:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "4f:10:06:b3:ac:b5:5f:c6:ef:7f:a9:cb:5d:33:9d:10"
      - run: echo $REMOTE_HOSTKEY >> ~/.ssh/known_hosts
      - run: # change this to deploy; but docs said it would be disabled with ssh usages
          name: deploy
          command: |
            if [ "${CIRCLE_BRANCH}" = "master" ]; then
              rsync -avce ssh ./frontend/build root@matthewpetschl.com:/www/lol
            else
              echo "Not master branch, dry run only"
            fi 