version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:latest
    environment:
      LOL: u
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            yarn
            yarn build
            cd build
            ls -la
      - run:
          command: |
            cd backend
            yarn
            yarn start:background
            curl http://localhost:3000/